### ISSUE TITLE
请教下，这种博客怎么搭建的？

### ISSUE THREAD

**Issue by Lotus-Blue** [snowdreams1006/snowdreams1006.github.io#104]
多谢指教，是不是只需要fork就行了？

**Comment by snowdreams1006** [comment]
先使用 git 克隆项目到本地,再使用 gitbook 运行本地项目即可查看效果,fork 是没必要的,详情可以查看关于 gitbook 的教程.

**Comment by Lotus-Blue** [comment]
> 先使用 git 克隆项目到本地,再使用 gitbook 运行本地项目即可查看效果,fork 是没必要的,详情可以查看关于 gitbook 的教程.

ok，多谢指点
